export default {
    GET_LEAGUES_INFO: 'GET_LEAGUES_INFO',
    GET_SEASONS_INFO: 'GET_SEASONS_INFO',
    GET_TEAM_INFO: 'GET_TEAM_INFO',
    GET_TEAMS_INFO: 'GET_TEAMS_INFO',
    GET_SCORERS_INFO: 'GET_SCORERS_INFO',
    GET_PLAYER_INFO: 'GET_PLAYER_INFO',
    
    REMOVE_TEAM_INFO: 'REMOVE_TEAM_INFO',
    REMOVE_PLAYER_INFO: 'REMOVE_PLAYER_INFO',

    SHOW_ERROR_MSG: 'SHOW_ERROR_MSG'
}